// If `APCA_DEBUG` false, console.debug() should not log anything.
if (JSON.parse(Deno.env.get("APCA_DEBUG") || "false")) {
  console.debug = () => {};
} else {
  // Prefix all debug logs with "@alpacahq/typescript-sdk" to make it easier to
  // for users to filter out debug logs from this SDK.
  console.debug = (...args) =>
    console.log("@alpacahq/typescript-sdk:debug", ...args);
}
export {
  type CashDividend,
  type CashMerger,
  type CorporateActions,
  type CryptoBar,
  type CryptoBars,
  type CryptoBarsLatest,
  type CryptoOrderbook,
  type CryptoOrderbookEntry,
  type CryptoOrderbooksLatest,
  type CryptoQuote,
  type CryptoQuotes,
  type CryptoQuotesLatest,
  type CryptoSnapshots,
  type CryptoTrade,
  type CryptoTrades,
  type CryptoTradesLatest,
  type ForexRate,
  type ForexRates,
  type ForexRatesLatest,
  type ForwardSplit,
  getCryptoBars,
  type GetCryptoBarsLatestOptions,
  type GetCryptoBarsOptions,
  type GetCryptoOrderbooksLatestOptions,
  getCryptoQuotes,
  getCryptoQuotesLatest,
  type GetCryptoQuotesLatestOptions,
  type GetCryptoQuotesOptions,
  getCryptoSnapshots,
  type GetCryptoSnapshotsOptions,
  getCryptoTrades,
  getCryptoTradesLatest,
  type GetCryptoTradesLatestOptions,
  type GetCryptoTradesOptions,
  getForexRates,
  type GetForexRatesLatestOptions,
  type GetForexRatesOptions,
  getLatestCryptoBars,
  getLatestCryptoOrderbooks,
  getLatestForexRates,
  getLogo,
  type GetLogoOptions,
  getNews,
  type GetNewsOptions,
  getOptionsBars,
  type GetOptionsBarsOptions,
  getOptionsExchanges,
  getOptionsSnapshots,
  type GetOptionsSnapshotsOptions,
  getOptionsTrades,
  getOptionsTradesLatest,
  type GetOptionsTradesLatestOptions,
  type GetOptionsTradesOptions,
  getStocksAuctions,
  type GetStocksAuctionsOptions,
  getStocksBars,
  getStocksBarsLatest,
  type GetStocksBarsLatestOptions,
  type GetStocksBarsOptions,
  getStocksConditions,
  type GetStocksConditionsOptions,
  getStocksCorporateActions,
  type GetStocksCorporateActionsOptions,
  getStocksExchangeCodes,
  getStocksMarketMovers,
  type GetStocksMarketMoversOptions,
  getStocksMostActives,
  type GetStocksMostActivesOptions,
  getStocksQuotes,
  getStocksQuotesLatest,
  type GetStocksQuotesLatestOptions,
  type GetStocksQuotesOptions,
  getStocksSnapshots,
  type GetStocksSnapshotsOptions,
  getStocksTrades,
  getStocksTradesLatest,
  type GetStocksTradesLatestOptions,
  type GetStocksTradesOptions,
  type Logo,
  type MarketMover,
  type MarketMovers,
  type MostActive,
  type MostActives,
  type NameChange,
  type OptionBar,
  type OptionsBars,
  type OptionsExchanges,
  type OptionsSnapshots,
  type OptionsSnapshotsQuote,
  type OptionsSnapshotsTrade,
  type OptionsTrades,
  type OptionsTradesLatest,
  type Redemption,
  type ReverseSplit,
  type Sort,
  type SpinOff,
  type StockAndCashMerger,
  type StockBar,
  type StockDividend,
  type StockMerger,
  type StockQuote,
  type StocksAuction,
  type StocksAuctionPrice,
  type StocksAuctions,
  type StocksBar,
  type StocksBars,
  type StocksBarsLatest,
  type StocksConditions,
  type StocksExchangeCodes,
  type StockSnapshots,
  type StocksQuotes,
  type StocksQuotesLatest,
  type StocksTrades,
  type StocksTradesLatest,
  type StockTrade,
  type UnitSplit,
  type WorthlessRemoval,
} from "./api/marketData.ts";

export {
  type Account,
  type AccountStatus,
  type Activity,
  type Asset,
  type BaseOrder,
  type Calendar,
  cancelOrder,
  type CancelOrderOptions,
  cancelOrders,
  type Clock,
  closePosition,
  type ClosePositionOptions,
  closePositions,
  type Configurations,
  type CorporateAction,
  createCryptoTransfer,
  type CreateCryptoTransferOptions,
  createOrder,
  type CreateOrderOptions,
  createWatchlist,
  type CreateWatchlistOptions,
  type CryptoFee,
  type CryptoOrder,
  type CryptoTransfer,
  type CryptoTransferResponse,
  type CryptoWallet,
  deleteWatchlist,
  type DeleteWatchlistOptions,
  type Direction,
  type EquityOrder,
  type ExerciseOption,
  exerciseOption,
  getAccount,
  getActivities,
  getActivity,
  type GetActivityOptions,
  getAsset,
  type GetAssetOptions,
  getAssets,
  type GetAssetsOptions,
  getCalendar,
  type GetCalendarOptions,
  getClock,
  getConfigurations,
  getCorporateAction,
  type GetCorporateActionOptions,
  getCorporateActions,
  type GetCorporateActionsOptions,
  type GetCryptoFeeEstimateOptions,
  getCryptoTransfer,
  type GetCryptoTransferOptions,
  getCryptoTransfers,
  type GetCryptoTransfersOptions,
  getCryptoWallet,
  getCryptoWallets,
  getCryptoWhitelistedAddress,
  getCryptoWhitelistedAddresses,
  type GetCryptoWhitelistedAddressOptions,
  getFeeEstimate,
  getOptionsContract,
  type GetOptionsContractOptions,
  getOptionsContracts,
  type GetOptionsContractsOptions,
  getOrder,
  type GetOrderOptions,
  getOrders,
  type GetOrdersOptions,
  getPortfolioHistory,
  type GetPortfolioHistoryOptions,
  getPosition,
  type GetPositionOptions,
  getPositions,
  type GetWalletOptions,
  getWatchlist,
  type GetWatchlistOptions,
  getWatchlists,
  type NonTradeActivity,
  type OptionsApprovedLevel,
  type OptionsContract,
  type OptionsOrder,
  type OptionsTradingLevel,
  type Order,
  type OrderClass,
  type PortfolioHistory,
  type PositionIntent,
  removeCryptoWhitelistedAddress,
  type RemoveCryptoWhitelistedAddressOptions,
  replaceOrder,
  type ReplaceOrderOptions,
  requestCryptoWhitelistedAddress,
  type RequestCryptoWhitelistedAddressOptions,
  type Side,
  type StopLoss,
  type TakeProfit,
  type TimeInForce,
  type TradingActivity,
  type Type,
  type UnstableNumber,
  updateConfigurations,
  type UpdateConfigurationsOptions,
  updateWatchlist,
  type UpdateWatchlistOptions,
  type Watchlist,
  type WhitelistedAddress,
} from "./api/trade.ts";

export {
  baseURLs,
  type Client,
  type ClientContext,
  createClient,
  type CreateClientOptions,
  type RequestOptions,
} from "./factory/createClient.ts";

export {
  createTokenBucket,
  type TokenBucketOptions,
} from "./factory/createTokenBucket.ts";

export {
  type MockFetch,
  mockFetch,
  type MockResponse,
} from "./util/mockFetch.ts";
